#!/bin/bash

# Import the settings from the common settings file
source ../project-settings.sh


#create Instance with metadata which contains the bucket info to push the logs once startup script has been completed to the bucket.
gcloud beta compute --project=$PROJECT_NAME instances create $VM_INSTANCE_NAME \
        --zone=us-central1-a \
        --machine-type=f1-micro \
        --subnet=default --network-tier=PREMIUM \
        --metadata=^,@^lab-logs-bucket=gs://$BUCKET_NAME/,@startup-script=\#\!\ /bin/bash$'\n'$'\n'\#$'\n'\#\ Echo\ commands\ as\ they\ are\ run,\ to\ make\ debugging\ easier.$'\n'\#\ GCE\ startup\ script\ output\ shows\ up\ in\ \"/var/log/syslog\"\ .$'\n'\#$'\n'set\ -x$'\n'$'\n'$'\n'\#$'\n'\#\ Stop\ apt-get\ calls\ from\ trying\ to\ bring\ up\ UI.$'\n'\#$'\n'export\ DEBIAN_FRONTEND=noninteractive$'\n'$'\n'$'\n'\#$'\n'\#\ Make\ sure\ installed\ packages\ are\ up\ to\ date\ with\ all\ security\ patches.$'\n'\#$'\n'apt-get\ -yq\ update$'\n'apt-get\ -yq\ upgrade$'\n'$'\n'$'\n'\#$'\n'\#\ Install\ Google\'s\ Stackdriver\ logging\ agent,\ as\ per$'\n'\#\ https://cloud.google.com/logging/docs/agent/installation$'\n'\#$'\n'curl\ -sSO\ https://dl.google.com/cloudagents/install-logging-agent.sh$'\n'bash\ install-logging-agent.sh$'\n'$'\n'$'\n'\#$'\n'\#\ Install\ and\ run\ the\ \"stress\"\ tool\ to\ max\ the\ CPU\ load\ for\ a\ while.$'\n'\#$'\n'apt-get\ -yq\ install\ stress$'\n'stress\ -c\ 8\ -t\ 120$'\n'$'\n'$'\n'\#$'\n'\#\ Report\ that\ we\'re\ done.$'\n'\#$'\n'$'\n'\#\ Metadata\ should\ be\ set\ in\ the\ \"lab-logs-bucket\"\ attribute\ using\ the\ \"gs://mybucketname/\"\ format.$'\n'log_bucket_metadata_name=lab-logs-bucket$'\n'log_bucket_metadata_url=\"http://metadata.google.internal/computeMetadata/v1/instance/attributes/\$\{log_bucket_metadata_name\}\"$'\n'worker_log_bucket=\$\(curl\ -H\ \"Metadata-Flavor:\ Google\"\ \"\$\{log_bucket_metadata_url\}\"\)$'\n'$'\n'\#\ We\ write\ a\ file\ named\ after\ this\ machine.$'\n'worker_log_file=\"machine-\$\(hostname\)-finished.txt\"$'\n'echo\ \"Phew\!\ \ Work\ completed\ at\ \$\(date\)\"\ \>\"\$\{worker_log_file\}\"$'\n'$'\n'\#\ And\ we\ copy\ that\ file\ to\ the\ bucket\ specified\ in\ the\ metadata.$'\n'echo\ \"Copying\ the\ log\ file\ to\ the\ bucket...\"$'\n'gsutil\ cp\ \"\$\{worker_log_file\}\"\ \"\$\{worker_log_bucket\}\" \ --maintenance-policy=MIGRATE --scopes=https://www.googleapis.com/auth/cloud-platform --image=debian-9-stretch-v20200902 --image-project=debian-cloud --boot-disk-size=10GB --boot-disk-type=pd-standard --boot-disk-device-name=instance-1 --reservation-affinity=any